### ISSUE TITLE
DOMException [InvalidStateError]: RTCDataChannel.readyState is not 'open'

### ISSUE THREAD

**Issue by jerryoldson** [mertushka/haxball.js#25]
I'm having the same issue as in #17 .

DOMException [InvalidStateError]: RTCDataChannel.readyState is not 'open'
    at RTCDataChannel.send (/home/facundocachuzumba/node_modules/�[4m@koush�[24m/wrtc/lib/index.js:49:8)
    at Na.mb (/home/facundocachuzumba/node_modules/�[4mhaxball.js�[24m/src/index.js:981:17)
    at Ja.mb (/home/facundocachuzumba/node_modules/�[4mhaxball.js�[24m/src/index.js:1846:17)
    at Fa.ad (/home/facundocachuzumba/node_modules/�[4mhaxball.js�[24m/src/index.js:1727:21)
    at Fa.zh (/home/facundocachuzumba/node_modules/�[4mhaxball.js�[24m/src/index.js:1838:44)
    at Fa.wh (/home/facundocachuzumba/node_modules/�[4mhaxball.js�[24m/src/index.js:1793:22)
    at a.$e (/home/facundocachuzumba/node_modules/�[4mhaxball.js�[24m/src/index.js:1685:15)
    at Na.e.onmessage (/home/facundocachuzumba/node_modules/�[4mhaxball.js�[24m/src/index.js:392:66)
    at /home/facundocachuzumba/node_modules/�[4m@koush�[24m/wrtc/lib/eventtarget.js:37:18
    at Set.forEach (<anonymous>)

Don't know how to reproduce it.

**Comment by mertushka** [comment]
This bug may have been fixed in `v2.2.0`. Closing as solved for now, follow-up needed.
