### ISSUE TITLE
Support for WebRTC ARM64

### ISSUE THREAD

**Issue by akafc7** [mertushka/haxball.js#37]
```
/home/ubuntu/AmebasTS/node_modules/@roamhq/wrtc/lib/binding.js:27
  throw new Error(Could not find wrtc binary on any of the paths: ${paths_to_try});
        ^
Error: Could not find wrtc binary on any of the paths: ../build-linux-arm64/wrtc.node,../build-linux-arm64/Debug/wrtc.node,../build-linux-arm64/Release/wrtc.node,@roamhq/wrtc-linux-arm64,./node_modules/@roamhq/wrtc-linux-arm64,./node_modules/@roamhq/wrtc-linux-arm64/wrtc.node
    at Object.<anonymous> (/home/ubuntu/AmebasTS/node_modules/@roamhq/wrtc/lib/binding.js:27:9)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Object.require.extensions.<computed> [as .js] (/home/ubuntu/AmebasTS/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/ubuntu/AmebasTS/node_modules/@roamhq/wrtc/lib/index.js:23:5)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
```

**Comment by akafc7** [comment]
```
ubuntu@instance-20220716-0418:~/AmebasTS$ uname -m
aarch64
ubuntu@instance-20220716-0418:~/AmebasTS$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by mertushka** [comment]
It should've prebuilds for linux-arm64, although you can try to build wrtc module from source.

https://github.com/WonderInventions/node-webrtc?tab=readme-ov-file#supported-platforms

https://github.com/WonderInventions/node-webrtc/blob/develop/docs/build-from-source.md

**Comment by mertushka** [comment]
Also, you can try changing WebRTC module that haxball.js currently uses. I don't prefer them because they are deprecated, you can give it a try. 

[wrtc](https://www.npmjs.com/package/wrtc)
[@koush/wrtc](https://www.npmjs.com/package/@koush/wrtc)

**Comment by mertushka** [comment]
Please follow-up in #38
